// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['main']['App']['Add'](arg1, arg2);
}

export function Backspace(arg1) {
  return window['go']['main']['App']['Backspace'](arg1);
}

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function ClearMemory() {
  return window['go']['main']['App']['ClearMemory']();
}

export function DigitNumber(arg1, arg2) {
  return window['go']['main']['App']['DigitNumber'](arg1, arg2);
}

export function DigitOperation(arg1, arg2, arg3) {
  return window['go']['main']['App']['DigitOperation'](arg1, arg2, arg3);
}

export function Divide(arg1, arg2) {
  return window['go']['main']['App']['Divide'](arg1, arg2);
}

export function Multiply(arg1, arg2) {
  return window['go']['main']['App']['Multiply'](arg1, arg2);
}

export function Subtract(arg1, arg2) {
  return window['go']['main']['App']['Subtract'](arg1, arg2);
}
