// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backspace(arg1) {
  return window['go']['main']['App']['Backspace'](arg1);
}

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function ClearMemory() {
  return window['go']['main']['App']['ClearMemory']();
}

export function DigitNumber(arg1, arg2) {
  return window['go']['main']['App']['DigitNumber'](arg1, arg2);
}
