// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backspace(arg1:string):Promise<string>;

export function Clear():Promise<string>;

export function DigitNumber(arg1:number,arg2:string):Promise<string>;
