// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string,arg2:string):Promise<number>;

export function Backspace(arg1:string):Promise<string>;

export function Clear():Promise<string>;

export function ClearMemory():Promise<string>;

export function DigitNumber(arg1:number,arg2:string):Promise<string>;

export function DigitOperation(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function Divide(arg1:string,arg2:string):Promise<number>;

export function Multiply(arg1:string,arg2:string):Promise<number>;

export function Subtract(arg1:string,arg2:string):Promise<number>;
